return {
  -- ============================================
  -- Avante: Copilot-Style Autocomplete (local)
  -- Uses: qwen2.5-coder:7b (fast)
  -- ============================================
--   {
--     "yetone/avante.nvim",
--     event = "VeryLazy",
--     lazy = false,
--     version = false,
--     build = "make",
--     dependencies = {
--       "nvim-treesitter/nvim-treesitter",
--       "stevearc/dressing.nvim",
--       "nvim-lua/plenary.nvim",
--       "MunifTanjim/nui.nvim",
--       "nvim-tree/nvim-web-devicons",
--     },
--     opts = {
--       provider = "ollama",
--       auto_suggestions_provider = "ollama",
--       vendors = {
--         ollama = {
--           __inherited_from = "openai",
--           api_key_name = "",
--           endpoint = "http://127.0.0.1:11434/v1",
--           model = "qwen2.5-coder:7b",
--           timeout = 30000,
--           temperature = 0,
--
--           -- 4096 is huge for autocomplete; smaller = faster
--           max_tokens = 128,
--         },
--       },
--       behaviour = {
--         auto_suggestions = true,
--         auto_set_highlight_group = true,
--         auto_set_keymaps = true,
--         auto_apply_diff_after_generation = false,
--         support_paste_from_clipboard = false,
--       },
--       mappings = {
--         diff = {
--           ours = "co",
--           theirs = "ct",
--           all_theirs = "ca",
--           both = "cb",
--           cursor = "cc",
--           next = "]x",
--           prev = "[x",
--         },
--         suggestion = {
--           accept = "<Tab>",
--           next = "<M-]>",
--           prev = "<M-[>",
--           dismiss = "<C-]>",
--         },
--         jump = {
--           next = "]]",
--           prev = "[[",
--         },
--         submit = {
--           normal = "<CR>",
--           insert = "<C-s>",
--         },
--       },
--       hints = { enabled = true },
--       windows = {
--         position = "right",
--         wrap = true,
--         width = 30,
--         sidebar_header = {
--           align = "center",
--           rounded = true,
--         },
--       },
--       highlights = {
--         diff = {
--           current = "DiffText",
--           incoming = "DiffAdd",
--         },
--       },
--       diff = {
--         autojump = true,
--         list_opener = "copen",
--       },
--     },
--   },

  -- ============================================
  -- Disable Copilot (we're using local models)
  -- ============================================
  { "github/copilot.vim", enabled = false },
  { "zbirenbaum/copilot.lua", enabled = false },
}
